[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/robots.txt"
  to = "/test0/robots.txt"
  status = 301
#  force = true
[[redirects]]
  from = "/test0/robots.txt"
  to = "/test1/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test1/robots.txt"
  to = "/test2/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test2/robots.txt"
  to = "/test3/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test3/robots.txt"
  to = "/test4/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test4/robots.txt"
  to = "/test5/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test5/robots.txt"
  to = "/test6/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test6/robots.txt"
  to = "/test7/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test7/robots.txt"
  to = "/test8/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test8/robots.txt"
  to = "/test9/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test9/robots.txt"
  to = "/test10/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test10/robots.txt"
  to = "/test11/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test11/robots.txt"
  to = "/test12/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test12/robots.txt"
  to = "/test13/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test13/robots.txt"
  to = "/test14/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test14/robots.txt"
  to = "/test15/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test15/robots.txt"
  to = "/test16/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test16/robots.txt"
  to = "/test17/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test17/robots.txt"
  to = "/test18/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test18/robots.txt"
  to = "/test19/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test19/robots.txt"
  to = "/test20/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test20/robots.txt"
  to = "/test21/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test21/robots.txt"
  to = "/test22/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test22/robots.txt"
  to = "/test23/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test23/robots.txt"
  to = "/test24/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test24/robots.txt"
  to = "/test25/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test25/robots.txt"
  to = "/test26/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test26/robots.txt"
  to = "/test27/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test27/robots.txt"
  to = "/test28/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test28/robots.txt"
  to = "/test29/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test29/robots.txt"
  to = "/test30/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test30/robots.txt"
  to = "/test31/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test31/robots.txt"
  to = "/test32/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test32/robots.txt"
  to = "/test33/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test33/robots.txt"
  to = "/test34/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test34/robots.txt"
  to = "/test35/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test35/robots.txt"
  to = "/test36/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test36/robots.txt"
  to = "/test37/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test37/robots.txt"
  to = "/test38/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test38/robots.txt"
  to = "/test39/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test39/robots.txt"
  to = "/test40/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test40/robots.txt"
  to = "/test41/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test41/robots.txt"
  to = "/test42/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test42/robots.txt"
  to = "/test43/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test43/robots.txt"
  to = "/test44/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test44/robots.txt"
  to = "/test45/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test45/robots.txt"
  to = "/test46/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test46/robots.txt"
  to = "/test47/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test47/robots.txt"
  to = "/test48/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test48/robots.txt"
  to = "/test49/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test49/robots.txt"
  to = "/test50/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test50/robots.txt"
  to = "/test51/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test51/robots.txt"
  to = "/test52/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test52/robots.txt"
  to = "/test53/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test53/robots.txt"
  to = "/test54/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test54/robots.txt"
  to = "/test55/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test55/robots.txt"
  to = "/test56/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test56/robots.txt"
  to = "/test57/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test57/robots.txt"
  to = "/test58/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test58/robots.txt"
  to = "/test59/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test59/robots.txt"
  to = "/test60/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test60/robots.txt"
  to = "/test61/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test61/robots.txt"
  to = "/test62/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test62/robots.txt"
  to = "/test63/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test63/robots.txt"
  to = "/test64/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test64/robots.txt"
  to = "/test65/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test65/robots.txt"
  to = "/test66/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test66/robots.txt"
  to = "/test67/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test67/robots.txt"
  to = "/test68/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test68/robots.txt"
  to = "/test69/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test69/robots.txt"
  to = "/test70/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test70/robots.txt"
  to = "/test71/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test71/robots.txt"
  to = "/test72/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test72/robots.txt"
  to = "/test73/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test73/robots.txt"
  to = "/test74/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test74/robots.txt"
  to = "/test75/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test75/robots.txt"
  to = "/test76/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test76/robots.txt"
  to = "/test77/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test77/robots.txt"
  to = "/test78/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test78/robots.txt"
  to = "/test79/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test79/robots.txt"
  to = "/test80/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test80/robots.txt"
  to = "/test81/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test81/robots.txt"
  to = "/test82/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test82/robots.txt"
  to = "/test83/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test83/robots.txt"
  to = "/test84/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test84/robots.txt"
  to = "/test85/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test85/robots.txt"
  to = "/test86/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test86/robots.txt"
  to = "/test87/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test87/robots.txt"
  to = "/test88/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test88/robots.txt"
  to = "/test89/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test89/robots.txt"
  to = "/test90/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test90/robots.txt"
  to = "/test91/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test91/robots.txt"
  to = "/test92/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test92/robots.txt"
  to = "/test93/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test93/robots.txt"
  to = "/test94/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test94/robots.txt"
  to = "/test95/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test95/robots.txt"
  to = "/test96/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test96/robots.txt"
  to = "/test97/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test97/robots.txt"
  to = "/test98/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test98/robots.txt"
  to = "/test99/robots.txt"
  status = 301
  force = true
[[redirects]]
  from = "/test99/robots.txt"
  to = "/test100/robots.txt"
  status = 301
  force = true
